{% set python_min = '3.10' %}
{% set version = "0.0.16" %}

package:
  name: auditwheel-emscripten
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/auditwheel-emscripten/auditwheel_emscripten-{{ version }}.tar.gz
  sha256: 049ba7ef502921aec655f61a69362716de3c043694c294494f73909e805bc1a4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - leb128
    - packaging
    - pyodide-cli
    - python >={{ python_min }}
    - typer-slim
    - wheel

test:
  imports:
    - auditwheel_emscripten
  commands:
    - pip check
    - pyodide auditwheel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/auditwheel-emscripten
  summary: auditwheel-like tool for Pyodide
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/ryanking13/auditwheel-emscripten

extra:
  recipe-maintainers:
    - bollwyvl
