{% set version = "0.0.14" %}

package:
  name: auditwheel-emscripten
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/auditwheel-emscripten/auditwheel_emscripten-{{ version }}.tar.gz
  sha256: 7067033b3abcf20101c94ee4553e6cc8fd0c77fca1bd0e6fc01f3a99de892f1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.10
  run:
    - leb128
    - packaging
    - pyodide-cli
    - python >=3.10
    - typer
    - wheel

test:
  imports:
    - auditwheel_emscripten
  commands:
    - pip check
    - pyodide auditwheel --help
  requires:
    - pip

about:
  home: https://pypi.org/project/auditwheel-emscripten
  summary: auditwheel-like tool for Pyodide
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/ryanking13/auditwheel-emscripten

extra:
  recipe-maintainers:
    - bollwyvl
