{% set version = "0.0.13" %}

package:
  name: auditwheel-emscripten
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/auditwheel-emscripten/auditwheel_emscripten-{{ version }}.tar.gz
  sha256: 1b0a5293487561eed337d0658528b8eff895acd961ecd92d20cc8112a591a53d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.10
  run:
    - leb128
    - packaging
    - pyodide-cli
    - python >=3.10
    - typer
    - wheel

test:
  imports:
    - auditwheel_emscripten
  commands:
    - pip check
    - pyodide auditwheel --help
  requires:
    - pip

about:
  home: https://pypi.org/project/auditwheel-emscripten
  summary: auditwheel-like tool for Pyodide
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/ryanking13/auditwheel-emscripten

extra:
  recipe-maintainers:
    - bollwyvl
