# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.0"
  python_min: "3.12"
  python_check_max: "3.14"

package:
  name: auditwheel-emscripten
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/a/auditwheel-emscripten/auditwheel_emscripten-${{ version }}.tar.gz
  sha256: a58fbd4adc7573548146ea64e73b3f603cbb52c7f9269cdf711818c0e9d69854

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - leb128
    - packaging
    - pyodide-cli >=0.4
    - python >=${{ python_min }}
    - wheel

tests:
  - package_contents:
      strict: true
      site_packages:
        - auditwheel_emscripten/**
        - auditwheel_emscripten-${{ version }}.dist-info/**
  - python:
      imports:
        - auditwheel_emscripten
        - auditwheel_emscripten.cli.main
        - auditwheel_emscripten.emscripten_tools
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pyodide auditwheel --help

about:
  summary: auditwheel-like tool for Pyodide
  license: MPL-2.0 AND (MIT OR NCSA)
  license_file:
    - LICENSE
    - auditwheel_emscripten/emscripten_tools/LICENSE
  homepage: https://pypi.org/project/auditwheel-emscripten
  repository: https://github.com/pyodide/auditwheel-emscripten

extra:
  recipe-maintainers:
    - bollwyvl
    - agriyakhetarpal
